### ISSUE TITLE
[240117] OSI 7 layer

### ISSUE THREAD

**Issue by HumanIearning** [chijoon-study/cs-study#1]
🚀 스터디
시작일시 : 2024-01-17 (수)
참석자 : 3명(김도현, 양시준, 곽희상)
내용 : osi 7 layer의 개념에 대해 깊게 공부, 마크다운 파일로 정리 후 업로드
✍️ 스터디 방식
구글링을 통해 osi 7 layer에 대해 각자 공부
금주 일요일에 각자 발표 후 피드백 
osi7layer/각자 이름으로 브랜치 생성 후 network/osi7layer 아래에 각자 이름으로 마크다운 파일 생성 후 main으로 PR올림 이후 발표날 이전까지 계속해서 공부 후 정리하며 마크다운 파일 수정 
남의 파일 변경사항을 지속적으로 추적하고 읽으며 해당 pr내에서 피드백

**Comment by YangSiJun528** [comment]
<읽자마자 it 전문가가 되는 네트워크 교과서> 책 가볍게 끝까지 읽었는데, 내용은 괜찮은 것 같아요.
글자 수도 적어서 3~4시간이면 충분히 볼 수 있었어요. 네트워크 기초적인 부분과 보안/익명성 관한 부분을 다루고 있어요. 

저는 표준 규칙을 정하는 여러 단체를 다루는게 좋았네요. 나중에 자료 찾을 때 참고용으로 몇 번 볼 듯.
보안/익명성 관련한 부분은 아마 저자가 Article 19(인터넷 관련 국제 인권 단체)라서 중요하게 다룬 것 같은데, 그 부분도 재미있게 봤네요.

**Comment by YangSiJun528** [comment]
[공지] 
커리큘럼 없이 주제만으로 진행하는건 어려움이 있다고 판단하여, 네트워크 스터디는 중지하였습니다.
(이후 특정 도서를 기준으로 스터디를 진행하기로 변경하였습니다.)
